# Generated by Django 5.1.1 on 2024-10-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_secret',
            new_name='mfa_secret',
        ),
    ]
