# Generated by Django 5.1.1 on 2024-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_otp_secret_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
